node {
      for (i=0; i<2; i++) { 
           stage "Stage #"+i
           print 'This is the stage #' +i
           if (i==0)
           {
               git "https://github.com/digitalvarys/jenkins-tutorials.git"
               echo 'Running on Stage #0'
           }
           else {
               build 'Declarative pipeline'
               echo 'Running on Stage #1'
           }
      }
}

