pipeline {
    agent any
    stages {

        stage('testing pipeline'){
          steps{
		    echo 'Demo - 1'
               // sh 'mkdir from-jenkins'
                sh 'touch from-jenkins/demo.txt'
		  //echo 'my first task is done'
		  //echo 'done tiggering'
                }
        }

}
}
